# Generated by Django 2.0.3 on 2018-03-25 08:38

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
	    HStoreExtension(),
    ]
