# Generated by Django 2.0.3 on 2018-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_exercise', '0002_song_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='songs',
            field=models.ManyToManyField(related_name='tags', to='drf_exercise.Song'),
        ),
    ]
